name: audioplayers_example
description: Demonstrates how to use the audioplayers plugin.

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.20.1
  http: ^0.13.1
  path_provider: ^2.0.1
  path_provider_macos: ^2.0.0
  provider: 5.0.0
  swipable_stack: ^1.0.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flame_lint: 0.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/audio1.mp3
    - assets/audio2.mp3
    - assets/audio3.mp3
    - assets/audio4.wav
    - assets/audio5.wav
    - assets/audio6.wav
    - assets/audio7.wav
    - assets/audio8.wav
    - assets/audio9.wav
    - assets/audio10.mp3
    - assets/audio11.mp3
    - assets/audio12.mp3
    - assets/audio13.mp3
    - assets/audio14.mp3

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.10.0"